export const actions = {
    CREATE_EVENT: "CREATE_EVENT",
    DELETE_EVENT: "DELETE_EVENT",
    DELETE_ALL_EVENT: "DELETE_ALL_EVENT",

    ADD_OPERATION_LOG: "ADD_OPERATION_LOG",
    DELETE_ALL_OPERATION_LOG: "DELETE_ALL_OPERATION_LOG",
}